### ISSUE TITLE
kaj kore na vhil 

### ISSUE THREAD

**Issue by uddin9live** [sh0umik/Laravel5-PaypalIPN#1]
kaj kore na vhi. composer update dile error asee

**Comment by thebdcoder** [comment]
Error Ta Paste korun .. Ami nijei use korci , sob thik ase ... composer require na use kore , manually 
"fahim/laravel5-paypal-ipn": "dev-master@dev" entry koren noito error dekhate pare ...

**Comment by uddin9live** [comment]
Thanks vhi . for the quick reply . i will get back to you if i face any problem .  and thanks for your  awesome work

**Comment by codingquark** [comment]
It's in dev state. Hope it is safe to use in production.

**Comment by thebdcoder** [comment]
i am using it in production .. its safe and recently updated with paypal changed policy
