### ISSUE TITLE
A release of this package

### ISSUE THREAD

**Issue by DannyFeliz** [sh0umik/Laravel5-PaypalIPN#7]
Hi man, could you please make a release of this package at least to `1.0` the thing is that is not recommended to install package from `dev-master` because you can upload new stuff that breaks something.

Hope you understand

**Comment by thebdcoder** [comment]
Ok i will

**Comment by DannyFeliz** [comment]
PING @thebdcoder 👀

**Comment by sh0umik** [comment]
@DannyFeliz , released 1.0.0 stable .. Apologies for late reply , I was busy on some other projects :)

**Comment by DannyFeliz** [comment]
Thanks!
